### ISSUE TITLE
请问 GrpcExampleServiceClient 是怎么生成的

### ISSUE THREAD

**Issue by eddyyuen** [overtly/core-grpc#3]
vs2019 通过 proto 生成的 cs 文件里面只有 GrpcExampleService 、GrpcExampleServiceBase ，请问 GrpcExampleServiceClient是使用哪个工具生成的？
--
是我设置错了

**Comment by mojinxun** [comment]
用这个，在扩展 => 管理扩展中可以搜索：《rpc menu》，
![image](https://user-images.githubusercontent.com/13127383/101012938-85279200-359e-11eb-9b1d-1dec8a583711.png)


如果下载比较慢的话，可以直接去VisualStudio的官方市场那边下载插件进行安装：
https://marketplace.visualstudio.com/items?itemName=yaofeng.rpctool
![image](https://user-images.githubusercontent.com/13127383/101012976-92dd1780-359e-11eb-99bd-d9362cd3ae75.png)

安装完后，对应的proto文件，右键就有了
![image](https://user-images.githubusercontent.com/13127383/101013090-ba33e480-359e-11eb-98ac-35c0720db8aa.png)
